# -*- coding: utf-8 -*-
"""Timepoint extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRbE9AyUIoEZERQnRGdB0wblFSqeJHiG
"""

import os
import SimpleITK as sitk

# Define your directories
base_dir = "/content"
images_dir = "/content/imagesTr"
output_dir = os.path.join(base_dir, "imagesTr_FLAIR")

# Create output directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

def extract_flair(input_image_path, output_image_path, flair_timepoint=0):
    img = sitk.ReadImage(input_image_path)
    size = img.GetSize()

    # Check if the image is 4D
    if len(size) < 4:
        print(f"Image {input_image_path} is not 4D. Copying as is.")
        sitk.WriteImage(img, output_image_path)
        return

    # Extract the FLAIR timepoint
    extractor = sitk.ExtractImageFilter()
    extraction_size = list(size)
    extraction_size[3] = 0

    extraction_index = [0, 0, 0, flair_timepoint]
    extractor.SetSize(extraction_size)
    extractor.SetIndex(extraction_index)
    flair_img = extractor.Execute(img)
    sitk.WriteImage(flair_img, output_image_path)

    print(f"Extracted FLAIR (timepoint {flair_timepoint}) from {input_image_path} and saved to {output_image_path}")

def extract_all_flairs(flair_timepoint=0):
    for filename in os.listdir(images_dir):
        if filename.endswith(('.nii.gz', '.nii')):
            input_path = os.path.join(images_dir, filename)

            # Keep the same filename but place in FLAIR output directory
            output_filename = filename
            # Alternatively, you could add "_FLAIR" to the filename:
            output_filename = filename.replace('.nii', '_FLAIR.nii') if filename.endswith('.nii') else filename.replace('.nii.gz', '_FLAIR.nii.gz')

            output_path = os.path.join(output_dir, output_filename)
            extract_flair(input_path, output_path, flair_timepoint)

FLAIR_TIMEPOINT = 0 #FLAIR is 0th channel, change flair_timepoint to 1,2,3 for other channel points
extract_all_flairs(flair_timepoint=FLAIR_TIMEPOINT)

print("FLAIR extraction complete. Files saved to:", output_dir)